table _Measures
	lineageTag: 76464ea5-7fe7-4f48-b1e3-e3882cb1f6d0

	measure 'Net Sales' = SUM(FactInternetSales[SalesAmount]) + SUM(FactStoreSales[SalesAmount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3f9be36f-4004-46be-983a-4f7e58ff7b00

	measure 'Net Sales_Internet' = SUM(FactInternetSales[SalesAmount])
		lineageTag: fde80eee-d629-46ec-81ce-12ee80b80bd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		dataType: string
		lineageTag: 9968fe63-6ca9-4744-8346-44a0300cb78e
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = {"Dummy"}

	annotation PBI_Id = f3521f79d45b411c8bba6d85c10bd68a

