table CategoryIcons
	lineageTag: b35554dd-6c1b-48f4-b7d6-6d23556cf8fa

	measure CategoryIcons =
			
			VAR folder_path = "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets"
			VAR accessories_icon_url = CONCATENATE(folder_path,"\accessories-64.png")
			
			RETURN accessories_icon_url
		lineageTag: 385c7b21-49c1-41e0-bf27-30b026135848

	column Category
		dataType: string
		lineageTag: 8e191b84-f365-43e8-91a9-386327977c24
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Category]

		annotation SummarizationSetBy = Automatic

	column 'Icon URL'
		dataType: string
		lineageTag: 757a7386-8bca-4c3e-aba7-240d464a1519
		dataCategory: ImageUrl
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Icon URL]

		annotation SummarizationSetBy = Automatic

	partition CategoryIcons = calculated
		mode: import
		source = ```
				
				VAR folder_path = "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets"
				VAR accessories_icon_url = CONCATENATE(folder_path,"\accessories-64.png")
				VAR bikes_icon_url = CONCATENATE(folder_path, "\bike-80.png")
				VAR clothing_icon_url = CONCATENATE(folder_path, "\clothing-96.png")
				VAR components_icon_url = CONCATENATE(folder_path, "\components-80.png")
				
				RETURN 
				
				DATATABLE(
				    "Category", STRING
				    , "Icon URL", STRING
				    , {
				        {"Accessories", "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets\accessories-64.png"}
				        , {"Bikes", "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets\bike-80.png"}
				        , {"Clothing", "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets\clothing-96.png"}
				        , {"Components", "C:\Users\RPascual - Finance\OneDrive - Sunnies Inc\Desktop\Sales-Data-Mart\AdventureWorks-Sales-DataMart\assets\components-80.png"}
				     }
				)
				```

	annotation PBI_Id = 76dfaf2655254ccbb1e1f401d3ff7cf1

