USE MAU_AdventureWorks2022_DW
GO

DROP TABLE IF EXISTS dbo.DimPromo

-- Create Promo Dimension Table
CREATE TABLE dbo.DimPromo (
	PromoUniqueID int IDENTITY(1,1) -- Autoincrementing Surrogate Key
	, Promo nvarchar(255) NOT NULL
	, DiscountPct float NOT NULL
	, [Type] nvarchar(50) NOT NULL 
	, Category nvarchar(50) NOT NULL 
	, StartDate date NOT NULL
	, EndDate date NOT NULL
	, IsActive int
	, MinQuantity int  NOT NULL
	, MaxQuantity int
	, DateCreated date NOT NULL
	, DateModified date NOT NULL
	, CONSTRAINT PK_DimPromo_PromoID PRIMARY KEY CLUSTERED (PromoUniqueID ASC) --TypeConstraint_NameTable_NameColumn
)

-- Populate DimPromo table
INSERT INTO dbo.DimPromo
SELECT 
	--PromoUniqueID int IDENTITY(1,1) -- Autogenerated through the IDENTITY property
      Promo = sso.[Description]
      ,DiscountPct = sso.DiscountPct
      ,[Type] = sso.[Type]
      ,Category = sso.Category
      ,StartDate = sso.StartDate
      ,EndDate = sso.EndDate
	  ,IsActive = CASE WHEN sso.StartDate <= GETDATE() AND (sso.EndDate IS NULL OR sso.EndDate >= GETDATE()) THEN 1 
					   WHEN sso.StartDate > GETDATE() OR sso.EndDate < GETDATE()  OR sso.StartDate IS NULL THEN 0
				  END
      ,MinQuantity = sso.MinQty
      ,MaxQuantity = sso.MaxQty
      ,DateCreated = GETDATE()
      ,DateModified = GETDATE()
FROM [AdventureWorks2022].[Sales].[SpecialOffer] sso

-- View Data
SELECT TOP(10) * FROM dbo.DimPromo